name: products.documentize.com
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@v4
      with:
          repository: smallize/documentize
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.135.0'
          extended: true
    - name: Determine Base URL
      id: base-url
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "url=https://products.documentize.com" >> $GITHUB_OUTPUT
        else
          echo "url=https://products-qa.documentize.com" >> $GITHUB_OUTPUT
        fi
    - name: Build
      run: hugo --config "configs/products.documentize.com.toml","configs/common.documentize.com.toml" -b "${{ steps.base-url.outputs.url }}" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
    - name: Deploy to Ceph (staging)
      if: ${{ github.event.inputs.environment == 'staging' }}
      run: hugo deploy --config "configs/products.documentize.com.toml" --maxDeletes=-1 --target "staging_ceph" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CEPH_QA_ROOT_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CEPH_QA_ROOT_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
    - name: Deploy to Ceph (production)
      if: ${{ github.event.inputs.environment == 'production' }}
      run: hugo deploy --config "configs/products.documentize.com.toml" --maxDeletes=-1 --target "production_ceph" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CEPH_PRODUCTS_DOCUMENTIZE_COM_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CEPH_PRODUCTS_DOCUMENTIZE_COM_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
